# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1086, 616)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName("tabWidget")
        self.Excel = QtWidgets.QWidget()
        self.Excel.setObjectName("Excel")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Excel)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolBox = QtWidgets.QToolBox(self.Excel)
        self.toolBox.setMaximumSize(QtCore.QSize(350, 16777215))
        self.toolBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toolBox.setObjectName("toolBox")
        self.ExcelMerge = QtWidgets.QWidget()
        self.ExcelMerge.setGeometry(QtCore.QRect(0, 0, 350, 466))
        self.ExcelMerge.setObjectName("ExcelMerge")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ExcelMerge)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.ExcelMerge)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_MergeExcelList = QtWidgets.QPushButton(self.groupBox)
        self.btn_MergeExcelList.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_MergeExcelList.setObjectName("btn_MergeExcelList")
        self.horizontalLayout.addWidget(self.btn_MergeExcelList)
        self.lineEditMergeExcelList = QtWidgets.QLineEdit(self.groupBox)
        self.lineEditMergeExcelList.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditMergeExcelList.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEditMergeExcelList.setObjectName("lineEditMergeExcelList")
        self.horizontalLayout.addWidget(self.lineEditMergeExcelList)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.ExcelMerge)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_SaveMergeExcel = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_SaveMergeExcel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_SaveMergeExcel.setObjectName("btn_SaveMergeExcel")
        self.horizontalLayout_2.addWidget(self.btn_SaveMergeExcel)
        self.lineEdit_SaveMergeExcel = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_SaveMergeExcel.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_SaveMergeExcel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_SaveMergeExcel.setObjectName("lineEdit_SaveMergeExcel")
        self.horizontalLayout_2.addWidget(self.lineEdit_SaveMergeExcel)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.btn_ExcelMerge = QtWidgets.QPushButton(self.ExcelMerge)
        self.btn_ExcelMerge.setObjectName("btn_ExcelMerge")
        self.verticalLayout_3.addWidget(self.btn_ExcelMerge)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.toolBox.addItem(self.ExcelMerge, "")
        self.ExcelDuplication = QtWidgets.QWidget()
        self.ExcelDuplication.setGeometry(QtCore.QRect(0, 0, 350, 466))
        self.ExcelDuplication.setObjectName("ExcelDuplication")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.ExcelDuplication)
        self.verticalLayout_10.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_3 = QtWidgets.QGroupBox(self.ExcelDuplication)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_DuplicationExcel = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_DuplicationExcel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_DuplicationExcel.setObjectName("btn_DuplicationExcel")
        self.horizontalLayout_4.addWidget(self.btn_DuplicationExcel)
        self.lineEditDuplicationExcel = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEditDuplicationExcel.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditDuplicationExcel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEditDuplicationExcel.setObjectName("lineEditDuplicationExcel")
        self.horizontalLayout_4.addWidget(self.lineEditDuplicationExcel)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.verticalLayout_10.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.ExcelDuplication)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_SaveDuplicationExcel = QtWidgets.QPushButton(self.groupBox_4)
        self.btn_SaveDuplicationExcel.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_SaveDuplicationExcel.setObjectName("btn_SaveDuplicationExcel")
        self.horizontalLayout_5.addWidget(self.btn_SaveDuplicationExcel)
        self.lineEdit_SaveDuplicationExcel = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_SaveDuplicationExcel.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_SaveDuplicationExcel.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_SaveDuplicationExcel.setObjectName("lineEdit_SaveDuplicationExcel")
        self.horizontalLayout_5.addWidget(self.lineEdit_SaveDuplicationExcel)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.ExcelDuplication)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_ExcelDuplicationCol = QtWidgets.QLabel(self.groupBox_5)
        self.label_ExcelDuplicationCol.setObjectName("label_ExcelDuplicationCol")
        self.horizontalLayout_6.addWidget(self.label_ExcelDuplicationCol)
        self.lineEdit_ExcelDuplicationCol = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_ExcelDuplicationCol.setMaximumSize(QtCore.QSize(240, 16777215))
        self.lineEdit_ExcelDuplicationCol.setObjectName("lineEdit_ExcelDuplicationCol")
        self.horizontalLayout_6.addWidget(self.lineEdit_ExcelDuplicationCol)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.btn_ExcelDuplication = QtWidgets.QPushButton(self.ExcelDuplication)
        self.btn_ExcelDuplication.setObjectName("btn_ExcelDuplication")
        self.verticalLayout_10.addWidget(self.btn_ExcelDuplication)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.toolBox.addItem(self.ExcelDuplication, "")
        self.ExcelRotate = QtWidgets.QWidget()
        self.ExcelRotate.setGeometry(QtCore.QRect(0, 0, 350, 466))
        self.ExcelRotate.setObjectName("ExcelRotate")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.ExcelRotate)
        self.verticalLayout_42.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_42.setSpacing(6)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.groupBox_22 = QtWidgets.QGroupBox(self.ExcelRotate)
        self.groupBox_22.setObjectName("groupBox_22")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.groupBox_22)
        self.verticalLayout_39.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_39.setSpacing(6)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setSpacing(22)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.btn_ExcelRotateFile = QtWidgets.QPushButton(self.groupBox_22)
        self.btn_ExcelRotateFile.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_ExcelRotateFile.setObjectName("btn_ExcelRotateFile")
        self.horizontalLayout_27.addWidget(self.btn_ExcelRotateFile)
        self.lineEdit_ExcelRotateFile = QtWidgets.QLineEdit(self.groupBox_22)
        self.lineEdit_ExcelRotateFile.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_ExcelRotateFile.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_ExcelRotateFile.setObjectName("lineEdit_ExcelRotateFile")
        self.horizontalLayout_27.addWidget(self.lineEdit_ExcelRotateFile)
        self.verticalLayout_39.addLayout(self.horizontalLayout_27)
        self.verticalLayout_42.addWidget(self.groupBox_22)
        self.groupBox_23 = QtWidgets.QGroupBox(self.ExcelRotate)
        self.groupBox_23.setObjectName("groupBox_23")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.groupBox_23)
        self.verticalLayout_40.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_40.setSpacing(6)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setSpacing(22)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.btn_SaveExcelRotate = QtWidgets.QPushButton(self.groupBox_23)
        self.btn_SaveExcelRotate.setMaximumSize(QtCore.QSize(60, 25))
        self.btn_SaveExcelRotate.setObjectName("btn_SaveExcelRotate")
        self.horizontalLayout_28.addWidget(self.btn_SaveExcelRotate)
        self.lineEdit_SaveExcelRotate = QtWidgets.QLineEdit(self.groupBox_23)
        self.lineEdit_SaveExcelRotate.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_SaveExcelRotate.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_SaveExcelRotate.setObjectName("lineEdit_SaveExcelRotate")
        self.horizontalLayout_28.addWidget(self.lineEdit_SaveExcelRotate)
        self.verticalLayout_40.addLayout(self.horizontalLayout_28)
        self.verticalLayout_42.addWidget(self.groupBox_23)
        self.groupBox_24 = QtWidgets.QGroupBox(self.ExcelRotate)
        self.groupBox_24.setObjectName("groupBox_24")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.groupBox_24)
        self.verticalLayout_41.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_41.setSpacing(6)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(6)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_ExcelRotatesheet = QtWidgets.QLabel(self.groupBox_24)
        self.label_ExcelRotatesheet.setObjectName("label_ExcelRotatesheet")
        self.horizontalLayout_29.addWidget(self.label_ExcelRotatesheet)
        self.lineEdit_ExcelRotatesheet = QtWidgets.QLineEdit(self.groupBox_24)
        self.lineEdit_ExcelRotatesheet.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit_ExcelRotatesheet.setMaximumSize(QtCore.QSize(16777215, 24))
        self.lineEdit_ExcelRotatesheet.setObjectName("lineEdit_ExcelRotatesheet")
        self.horizontalLayout_29.addWidget(self.lineEdit_ExcelRotatesheet)
        self.verticalLayout_41.addLayout(self.horizontalLayout_29)
        self.verticalLayout_42.addWidget(self.groupBox_24)
        self.btn_ExcelRotate = QtWidgets.QPushButton(self.ExcelRotate)
        self.btn_ExcelRotate.setObjectName("btn_ExcelRotate")
        self.verticalLayout_42.addWidget(self.btn_ExcelRotate)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_42.addItem(spacerItem2)
        self.toolBox.addItem(self.ExcelRotate, "")
        self.horizontalLayout_3.addWidget(self.toolBox)
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setSpacing(6)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Excel)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit_ExcelStatus = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit_ExcelStatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_ExcelStatus.setReadOnly(True)
        self.textEdit_ExcelStatus.setObjectName("textEdit_ExcelStatus")
        self.verticalLayout_6.addWidget(self.textEdit_ExcelStatus)
        self.tabWidget_2.addTab(self.tab_3, "")
        self.verticalLayout_30.addWidget(self.tabWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_30)
        self.tabWidget.addTab(self.Excel, "")
        self.Word = QtWidgets.QWidget()
        self.Word.setObjectName("Word")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.Word)
        self.horizontalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_21.setSpacing(6)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.toolBox_4 = QtWidgets.QToolBox(self.Word)
        self.toolBox_4.setMaximumSize(QtCore.QSize(320, 16777215))
        self.toolBox_4.setObjectName("toolBox_4")
        self.WordModuleUse = QtWidgets.QWidget()
        self.WordModuleUse.setGeometry(QtCore.QRect(0, 0, 196, 287))
        self.WordModuleUse.setObjectName("WordModuleUse")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.WordModuleUse)
        self.verticalLayout_35.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_35.setSpacing(6)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout()
        self.verticalLayout_34.setSpacing(6)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.groupBox_17 = QtWidgets.QGroupBox(self.WordModuleUse)
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_31.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_31.setSpacing(6)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setSpacing(6)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.btn_WordModule = QtWidgets.QPushButton(self.groupBox_17)
        self.btn_WordModule.setObjectName("btn_WordModule")
        self.horizontalLayout_22.addWidget(self.btn_WordModule)
        self.lineEdit_WordModule = QtWidgets.QLineEdit(self.groupBox_17)
        self.lineEdit_WordModule.setObjectName("lineEdit_WordModule")
        self.horizontalLayout_22.addWidget(self.lineEdit_WordModule)
        self.verticalLayout_31.addLayout(self.horizontalLayout_22)
        self.verticalLayout_34.addWidget(self.groupBox_17)
        self.groupBox_18 = QtWidgets.QGroupBox(self.WordModuleUse)
        self.groupBox_18.setObjectName("groupBox_18")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.groupBox_18)
        self.verticalLayout_32.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_32.setSpacing(6)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setSpacing(6)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.btn_WordModuleExcel = QtWidgets.QPushButton(self.groupBox_18)
        self.btn_WordModuleExcel.setObjectName("btn_WordModuleExcel")
        self.horizontalLayout_23.addWidget(self.btn_WordModuleExcel)
        self.lineEdit_WordModuleExcel = QtWidgets.QLineEdit(self.groupBox_18)
        self.lineEdit_WordModuleExcel.setObjectName("lineEdit_WordModuleExcel")
        self.horizontalLayout_23.addWidget(self.lineEdit_WordModuleExcel)
        self.verticalLayout_32.addLayout(self.horizontalLayout_23)
        self.verticalLayout_34.addWidget(self.groupBox_18)
        self.groupBox_19 = QtWidgets.QGroupBox(self.WordModuleUse)
        self.groupBox_19.setObjectName("groupBox_19")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.groupBox_19)
        self.verticalLayout_33.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_33.setSpacing(6)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setSpacing(6)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.btn_SaveWordModule = QtWidgets.QPushButton(self.groupBox_19)
        self.btn_SaveWordModule.setObjectName("btn_SaveWordModule")
        self.horizontalLayout_24.addWidget(self.btn_SaveWordModule)
        self.lineEdit_SaveWordModule = QtWidgets.QLineEdit(self.groupBox_19)
        self.lineEdit_SaveWordModule.setObjectName("lineEdit_SaveWordModule")
        self.horizontalLayout_24.addWidget(self.lineEdit_SaveWordModule)
        self.verticalLayout_33.addLayout(self.horizontalLayout_24)
        self.verticalLayout_34.addWidget(self.groupBox_19)
        self.btn_WordModuleTransform = QtWidgets.QPushButton(self.WordModuleUse)
        self.btn_WordModuleTransform.setObjectName("btn_WordModuleTransform")
        self.verticalLayout_34.addWidget(self.btn_WordModuleTransform)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_34.addItem(spacerItem3)
        self.verticalLayout_35.addLayout(self.verticalLayout_34)
        self.toolBox_4.addItem(self.WordModuleUse, "")
        self.Word_PDF = QtWidgets.QWidget()
        self.Word_PDF.setGeometry(QtCore.QRect(0, 0, 320, 484))
        self.Word_PDF.setObjectName("Word_PDF")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.Word_PDF)
        self.verticalLayout_38.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_38.setSpacing(6)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.groupBox_20 = QtWidgets.QGroupBox(self.Word_PDF)
        self.groupBox_20.setObjectName("groupBox_20")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.groupBox_20)
        self.verticalLayout_37.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_37.setSpacing(6)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setSpacing(6)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.btn_transWord = QtWidgets.QPushButton(self.groupBox_20)
        self.btn_transWord.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_transWord.setObjectName("btn_transWord")
        self.horizontalLayout_25.addWidget(self.btn_transWord)
        self.lineEdit_transWord = QtWidgets.QLineEdit(self.groupBox_20)
        self.lineEdit_transWord.setObjectName("lineEdit_transWord")
        self.horizontalLayout_25.addWidget(self.lineEdit_transWord)
        self.verticalLayout_37.addLayout(self.horizontalLayout_25)
        self.verticalLayout_38.addWidget(self.groupBox_20)
        self.groupBox_21 = QtWidgets.QGroupBox(self.Word_PDF)
        self.groupBox_21.setObjectName("groupBox_21")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.groupBox_21)
        self.verticalLayout_36.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_36.setSpacing(6)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setSpacing(6)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.btn_transPDF = QtWidgets.QPushButton(self.groupBox_21)
        self.btn_transPDF.setMaximumSize(QtCore.QSize(60, 16777215))
        self.btn_transPDF.setObjectName("btn_transPDF")
        self.horizontalLayout_26.addWidget(self.btn_transPDF)
        self.lineEdit_transPDF = QtWidgets.QLineEdit(self.groupBox_21)
        self.lineEdit_transPDF.setObjectName("lineEdit_transPDF")
        self.horizontalLayout_26.addWidget(self.lineEdit_transPDF)
        self.verticalLayout_36.addLayout(self.horizontalLayout_26)
        self.verticalLayout_38.addWidget(self.groupBox_21)
        self.btn_WordtoPDF = QtWidgets.QPushButton(self.Word_PDF)
        self.btn_WordtoPDF.setObjectName("btn_WordtoPDF")
        self.verticalLayout_38.addWidget(self.btn_WordtoPDF)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_38.addItem(spacerItem4)
        self.toolBox_4.addItem(self.Word_PDF, "")
        self.horizontalLayout_21.addWidget(self.toolBox_4)
        self.tabWidget_5 = QtWidgets.QTabWidget(self.Word)
        self.tabWidget_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_29.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_29.setSpacing(6)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.textEdit_WordStatus = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_WordStatus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_WordStatus.setReadOnly(True)
        self.textEdit_WordStatus.setObjectName("textEdit_WordStatus")
        self.verticalLayout_29.addWidget(self.textEdit_WordStatus)
        self.tabWidget_5.addTab(self.tab_5, "")
        self.horizontalLayout_21.addWidget(self.tabWidget_5)
        self.tabWidget.addTab(self.Word, "")
        self.PDF = QtWidgets.QWidget()
        self.PDF.setObjectName("PDF")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.PDF)
        self.horizontalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_20.setSpacing(6)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.toolBox_3 = QtWidgets.QToolBox(self.PDF)
        self.toolBox_3.setMaximumSize(QtCore.QSize(325, 16777215))
        self.toolBox_3.setObjectName("toolBox_3")
        self.PDFText = QtWidgets.QWidget()
        self.PDFText.setGeometry(QtCore.QRect(0, 0, 325, 514))
        self.PDFText.setObjectName("PDFText")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.PDFText)
        self.verticalLayout_28.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_28.setSpacing(6)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setSpacing(6)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.groupBox_16 = QtWidgets.QGroupBox(self.PDFText)
        self.groupBox_16.setObjectName("groupBox_16")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox_16)
        self.verticalLayout_26.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_26.setSpacing(6)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setSpacing(6)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btn_PDFTextfile = QtWidgets.QPushButton(self.groupBox_16)
        self.btn_PDFTextfile.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_PDFTextfile.setObjectName("btn_PDFTextfile")
        self.horizontalLayout_19.addWidget(self.btn_PDFTextfile)
        self.lineEdit_PDFTextfile = QtWidgets.QLineEdit(self.groupBox_16)
        self.lineEdit_PDFTextfile.setObjectName("lineEdit_PDFTextfile")
        self.horizontalLayout_19.addWidget(self.lineEdit_PDFTextfile)
        self.label_PDFTextpage = QtWidgets.QLabel(self.groupBox_16)
        self.label_PDFTextpage.setObjectName("label_PDFTextpage")
        self.horizontalLayout_19.addWidget(self.label_PDFTextpage)
        self.spinBox_PDFTextpage = QtWidgets.QSpinBox(self.groupBox_16)
        self.spinBox_PDFTextpage.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBox_PDFTextpage.setMinimum(1)
        self.spinBox_PDFTextpage.setMaximum(999999999)
        self.spinBox_PDFTextpage.setObjectName("spinBox_PDFTextpage")
        self.horizontalLayout_19.addWidget(self.spinBox_PDFTextpage)
        self.verticalLayout_26.addLayout(self.horizontalLayout_19)
        self.verticalLayout_27.addWidget(self.groupBox_16)
        self.btn_PDFTextgetpage = QtWidgets.QPushButton(self.PDFText)
        self.btn_PDFTextgetpage.setObjectName("btn_PDFTextgetpage")
        self.verticalLayout_27.addWidget(self.btn_PDFTextgetpage)
        self.btn_PDFTextgetpages = QtWidgets.QPushButton(self.PDFText)
        self.btn_PDFTextgetpages.setObjectName("btn_PDFTextgetpages")
        self.verticalLayout_27.addWidget(self.btn_PDFTextgetpages)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem5)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        self.toolBox_3.addItem(self.PDFText, "")
        self.horizontalLayout_20.addWidget(self.toolBox_3)
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setSpacing(6)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.textEdit_PDF = QtWidgets.QTextEdit(self.PDF)
        self.textEdit_PDF.setReadOnly(True)
        self.textEdit_PDF.setObjectName("textEdit_PDF")
        self.verticalLayout_25.addWidget(self.textEdit_PDF)
        self.tabWidget_4 = QtWidgets.QTabWidget(self.PDF)
        self.tabWidget_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_PDFStatus = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_PDFStatus.setObjectName("textEdit_PDFStatus")
        self.gridLayout_2.addWidget(self.textEdit_PDFStatus, 0, 0, 1, 1)
        self.tabWidget_4.addTab(self.tab_2, "")
        self.verticalLayout_25.addWidget(self.tabWidget_4)
        self.horizontalLayout_20.addLayout(self.verticalLayout_25)
        self.tabWidget.addTab(self.PDF, "")
        self.Email = QtWidgets.QWidget()
        self.Email.setObjectName("Email")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.Email)
        self.horizontalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.toolBox_2 = QtWidgets.QToolBox(self.Email)
        self.toolBox_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.toolBox_2.setObjectName("toolBox_2")
        self.TextEmail = QtWidgets.QWidget()
        self.TextEmail.setGeometry(QtCore.QRect(0, 0, 300, 484))
        self.TextEmail.setObjectName("TextEmail")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.TextEmail)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(6)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_6 = QtWidgets.QGroupBox(self.TextEmail)
        self.groupBox_6.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_TextEmailsmtpserver = QtWidgets.QLabel(self.groupBox_6)
        self.label_TextEmailsmtpserver.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_TextEmailsmtpserver.setObjectName("label_TextEmailsmtpserver")
        self.horizontalLayout_7.addWidget(self.label_TextEmailsmtpserver)
        self.comboBox_TextEmailsmtpserver = QtWidgets.QComboBox(self.groupBox_6)
        self.comboBox_TextEmailsmtpserver.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox_TextEmailsmtpserver.setObjectName("comboBox_TextEmailsmtpserver")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.comboBox_TextEmailsmtpserver.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_TextEmailsmtpserver)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_14.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.TextEmail)
        self.groupBox_7.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_11.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(22)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_TextEmailsenderemail = QtWidgets.QLabel(self.groupBox_7)
        self.label_TextEmailsenderemail.setObjectName("label_TextEmailsenderemail")
        self.horizontalLayout_8.addWidget(self.label_TextEmailsenderemail)
        self.lineEdit_TextEmailsenderemail = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_TextEmailsenderemail.setObjectName("lineEdit_TextEmailsenderemail")
        self.horizontalLayout_8.addWidget(self.lineEdit_TextEmailsenderemail)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_TextEmailsenderpassword = QtWidgets.QLabel(self.groupBox_7)
        self.label_TextEmailsenderpassword.setObjectName("label_TextEmailsenderpassword")
        self.horizontalLayout_9.addWidget(self.label_TextEmailsenderpassword)
        self.lineEdit_TextEmailsenderpassword = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_TextEmailsenderpassword.setObjectName("lineEdit_TextEmailsenderpassword")
        self.horizontalLayout_9.addWidget(self.lineEdit_TextEmailsenderpassword)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout_14.addWidget(self.groupBox_7)
        self.groupBox_8 = QtWidgets.QGroupBox(self.TextEmail)
        self.groupBox_8.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_12.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(22)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_TextEmailreceiveremail = QtWidgets.QLabel(self.groupBox_8)
        self.label_TextEmailreceiveremail.setObjectName("label_TextEmailreceiveremail")
        self.horizontalLayout_10.addWidget(self.label_TextEmailreceiveremail)
        self.lineEdit_TextEmailreceiveremail = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_TextEmailreceiveremail.setObjectName("lineEdit_TextEmailreceiveremail")
        self.horizontalLayout_10.addWidget(self.lineEdit_TextEmailreceiveremail)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_14.addWidget(self.groupBox_8)
        self.groupBox_9 = QtWidgets.QGroupBox(self.TextEmail)
        self.groupBox_9.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_13.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_13.setSpacing(6)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(22)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_TextEmailtitle = QtWidgets.QLabel(self.groupBox_9)
        self.label_TextEmailtitle.setObjectName("label_TextEmailtitle")
        self.horizontalLayout_11.addWidget(self.label_TextEmailtitle)
        self.lineEdit_TextEmailtitle = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_TextEmailtitle.setObjectName("lineEdit_TextEmailtitle")
        self.horizontalLayout_11.addWidget(self.lineEdit_TextEmailtitle)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.verticalLayout_14.addWidget(self.groupBox_9)
        self.btn_TextEmailclearcontent = QtWidgets.QPushButton(self.TextEmail)
        self.btn_TextEmailclearcontent.setObjectName("btn_TextEmailclearcontent")
        self.verticalLayout_14.addWidget(self.btn_TextEmailclearcontent)
        self.btn_TextEmailSend = QtWidgets.QPushButton(self.TextEmail)
        self.btn_TextEmailSend.setObjectName("btn_TextEmailSend")
        self.verticalLayout_14.addWidget(self.btn_TextEmailSend)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem6)
        self.toolBox_2.addItem(self.TextEmail, "")
        self.FileEmail = QtWidgets.QWidget()
        self.FileEmail.setGeometry(QtCore.QRect(0, 0, 272, 476))
        self.FileEmail.setObjectName("FileEmail")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.FileEmail)
        self.verticalLayout_24.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_24.setSpacing(6)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.groupBox_11 = QtWidgets.QGroupBox(self.FileEmail)
        self.groupBox_11.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_19.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_19.setSpacing(6)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(7)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_FileEmailsmtpserver = QtWidgets.QLabel(self.groupBox_11)
        self.label_FileEmailsmtpserver.setMaximumSize(QtCore.QSize(46, 16777215))
        self.label_FileEmailsmtpserver.setObjectName("label_FileEmailsmtpserver")
        self.horizontalLayout_13.addWidget(self.label_FileEmailsmtpserver)
        self.comboBox_FileEmailsmtpserver = QtWidgets.QComboBox(self.groupBox_11)
        self.comboBox_FileEmailsmtpserver.setMinimumSize(QtCore.QSize(170, 0))
        self.comboBox_FileEmailsmtpserver.setObjectName("comboBox_FileEmailsmtpserver")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.comboBox_FileEmailsmtpserver.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_FileEmailsmtpserver)
        self.verticalLayout_19.addLayout(self.horizontalLayout_13)
        self.verticalLayout_18.addWidget(self.groupBox_11)
        self.groupBox_12 = QtWidgets.QGroupBox(self.FileEmail)
        self.groupBox_12.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_20.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_20.setSpacing(6)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(22)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_FileEmailsenderemail = QtWidgets.QLabel(self.groupBox_12)
        self.label_FileEmailsenderemail.setObjectName("label_FileEmailsenderemail")
        self.horizontalLayout_14.addWidget(self.label_FileEmailsenderemail)
        self.lineEdit_FileEmailsenderemail = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_FileEmailsenderemail.setObjectName("lineEdit_FileEmailsenderemail")
        self.horizontalLayout_14.addWidget(self.lineEdit_FileEmailsenderemail)
        self.verticalLayout_20.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(6)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_FileEmailsenderpassword = QtWidgets.QLabel(self.groupBox_12)
        self.label_FileEmailsenderpassword.setObjectName("label_FileEmailsenderpassword")
        self.horizontalLayout_15.addWidget(self.label_FileEmailsenderpassword)
        self.lineEdit_FileEmailsenderpassword = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_FileEmailsenderpassword.setObjectName("lineEdit_FileEmailsenderpassword")
        self.horizontalLayout_15.addWidget(self.lineEdit_FileEmailsenderpassword)
        self.verticalLayout_20.addLayout(self.horizontalLayout_15)
        self.verticalLayout_18.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.FileEmail)
        self.groupBox_13.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_13.setObjectName("groupBox_13")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_21.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_21.setSpacing(6)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setSpacing(22)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_FileEmailreceiveremail = QtWidgets.QLabel(self.groupBox_13)
        self.label_FileEmailreceiveremail.setObjectName("label_FileEmailreceiveremail")
        self.horizontalLayout_16.addWidget(self.label_FileEmailreceiveremail)
        self.lineEdit_FileEmailreceiveremail = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_FileEmailreceiveremail.setObjectName("lineEdit_FileEmailreceiveremail")
        self.horizontalLayout_16.addWidget(self.lineEdit_FileEmailreceiveremail)
        self.verticalLayout_21.addLayout(self.horizontalLayout_16)
        self.verticalLayout_18.addWidget(self.groupBox_13)
        self.groupBox_14 = QtWidgets.QGroupBox(self.FileEmail)
        self.groupBox_14.setMaximumSize(QtCore.QSize(290, 16777215))
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_22.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_22.setSpacing(6)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setSpacing(22)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_FileEmailtitle = QtWidgets.QLabel(self.groupBox_14)
        self.label_FileEmailtitle.setObjectName("label_FileEmailtitle")
        self.horizontalLayout_17.addWidget(self.label_FileEmailtitle)
        self.lineEdit_FileEmailtitle = QtWidgets.QLineEdit(self.groupBox_14)
        self.lineEdit_FileEmailtitle.setObjectName("lineEdit_FileEmailtitle")
        self.horizontalLayout_17.addWidget(self.lineEdit_FileEmailtitle)
        self.verticalLayout_22.addLayout(self.horizontalLayout_17)
        self.verticalLayout_18.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.FileEmail)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_23.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_23.setSpacing(6)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setSpacing(6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.btn_FindFileEmail = QtWidgets.QPushButton(self.groupBox_15)
        self.btn_FindFileEmail.setMaximumSize(QtCore.QSize(46, 16777215))
        self.btn_FindFileEmail.setObjectName("btn_FindFileEmail")
        self.horizontalLayout_18.addWidget(self.btn_FindFileEmail)
        self.lineEdit_FindFileEmail = QtWidgets.QLineEdit(self.groupBox_15)
        self.lineEdit_FindFileEmail.setObjectName("lineEdit_FindFileEmail")
        self.horizontalLayout_18.addWidget(self.lineEdit_FindFileEmail)
        self.verticalLayout_23.addLayout(self.horizontalLayout_18)
        self.verticalLayout_18.addWidget(self.groupBox_15)
        self.btn_FileEmailclearcontent = QtWidgets.QPushButton(self.FileEmail)
        self.btn_FileEmailclearcontent.setObjectName("btn_FileEmailclearcontent")
        self.verticalLayout_18.addWidget(self.btn_FileEmailclearcontent)
        self.btn_FileEmailSend = QtWidgets.QPushButton(self.FileEmail)
        self.btn_FileEmailSend.setObjectName("btn_FileEmailSend")
        self.verticalLayout_18.addWidget(self.btn_FileEmailSend)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem7)
        self.verticalLayout_24.addLayout(self.verticalLayout_18)
        self.toolBox_2.addItem(self.FileEmail, "")
        self.horizontalLayout_12.addWidget(self.toolBox_2)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(6)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.groupBox_10 = QtWidgets.QGroupBox(self.Email)
        self.groupBox_10.setObjectName("groupBox_10")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_10)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit_emailContent = QtWidgets.QTextEdit(self.groupBox_10)
        self.textEdit_emailContent.setObjectName("textEdit_emailContent")
        self.gridLayout.addWidget(self.textEdit_emailContent, 0, 0, 1, 1)
        self.verticalLayout_17.addWidget(self.groupBox_10)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.Email)
        self.tabWidget_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_16.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.textEdit_emailstatus = QtWidgets.QTextEdit(self.tab)
        self.textEdit_emailstatus.setReadOnly(True)
        self.textEdit_emailstatus.setObjectName("textEdit_emailstatus")
        self.verticalLayout_16.addWidget(self.textEdit_emailstatus)
        self.tabWidget_3.addTab(self.tab, "")
        self.verticalLayout_17.addWidget(self.tabWidget_3)
        self.horizontalLayout_12.addLayout(self.verticalLayout_17)
        self.tabWidget.addTab(self.Email, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(3)
        self.tabWidget_2.setCurrentIndex(0)
        self.toolBox_4.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(0)
        self.toolBox_3.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(0)
        self.toolBox_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "选择文件夹"))
        self.btn_MergeExcelList.setText(_translate("MainWindow", "文件路径"))
        self.groupBox_2.setTitle(_translate("MainWindow", "保存路径"))
        self.btn_SaveMergeExcel.setText(_translate("MainWindow", "文件路径"))
        self.btn_ExcelMerge.setText(_translate("MainWindow", "合并"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ExcelMerge), _translate("MainWindow", "多表合并"))
        self.groupBox_3.setTitle(_translate("MainWindow", "选择路径"))
        self.btn_DuplicationExcel.setText(_translate("MainWindow", "文件路径"))
        self.groupBox_4.setTitle(_translate("MainWindow", "保存路径"))
        self.btn_SaveDuplicationExcel.setText(_translate("MainWindow", "文件路径"))
        self.groupBox_5.setTitle(_translate("MainWindow", "按列消除"))
        self.label_ExcelDuplicationCol.setText(_translate("MainWindow", "列名"))
        self.btn_ExcelDuplication.setText(_translate("MainWindow", "消除"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ExcelDuplication), _translate("MainWindow", "消除重复"))
        self.groupBox_22.setTitle(_translate("MainWindow", "选择路径"))
        self.btn_ExcelRotateFile.setText(_translate("MainWindow", "打开"))
        self.groupBox_23.setTitle(_translate("MainWindow", "保存路径"))
        self.btn_SaveExcelRotate.setText(_translate("MainWindow", "打开"))
        self.groupBox_24.setTitle(_translate("MainWindow", "选择工作簿"))
        self.label_ExcelRotatesheet.setText(_translate("MainWindow", "工作簿名称"))
        self.btn_ExcelRotate.setText(_translate("MainWindow", "旋转"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.ExcelRotate), _translate("MainWindow", "自动旋转"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Excel), _translate("MainWindow", "Excel"))
        self.groupBox_17.setTitle(_translate("MainWindow", "Word模板"))
        self.btn_WordModule.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_18.setTitle(_translate("MainWindow", "模板表格"))
        self.btn_WordModuleExcel.setText(_translate("MainWindow", "打开文件"))
        self.groupBox_19.setTitle(_translate("MainWindow", "保存路径"))
        self.btn_SaveWordModule.setText(_translate("MainWindow", "选择文件夹"))
        self.btn_WordModuleTransform.setText(_translate("MainWindow", "转换"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.WordModuleUse), _translate("MainWindow", "模板套用"))
        self.groupBox_20.setTitle(_translate("MainWindow", "Word路径"))
        self.btn_transWord.setText(_translate("MainWindow", "选择"))
        self.groupBox_21.setTitle(_translate("MainWindow", "保存路径"))
        self.btn_transPDF.setText(_translate("MainWindow", "选择"))
        self.btn_WordtoPDF.setText(_translate("MainWindow", "转换"))
        self.toolBox_4.setItemText(self.toolBox_4.indexOf(self.Word_PDF), _translate("MainWindow", " Word转PDF"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_5), _translate("MainWindow", "状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Word), _translate("MainWindow", "Word"))
        self.groupBox_16.setTitle(_translate("MainWindow", "属性"))
        self.btn_PDFTextfile.setText(_translate("MainWindow", "打开"))
        self.label_PDFTextpage.setText(_translate("MainWindow", "页数"))
        self.btn_PDFTextgetpage.setText(_translate("MainWindow", "提取该页"))
        self.btn_PDFTextgetpages.setText(_translate("MainWindow", "全部提取"))
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.PDFText), _translate("MainWindow", "文字提取"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_2), _translate("MainWindow", "状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.PDF), _translate("MainWindow", "PDF"))
        self.groupBox_6.setTitle(_translate("MainWindow", "服务器"))
        self.label_TextEmailsmtpserver.setText(_translate("MainWindow", "服务器"))
        self.comboBox_TextEmailsmtpserver.setItemText(0, _translate("MainWindow", "smtp.aliyun.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(1, _translate("MainWindow", "smtp.gmail.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(2, _translate("MainWindow", "smtp.sina.com.cn"))
        self.comboBox_TextEmailsmtpserver.setItemText(3, _translate("MainWindow", "smtp.tom.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(4, _translate("MainWindow", "smtp.163.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(5, _translate("MainWindow", "smtp.126.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(6, _translate("MainWindow", "smtp.qq.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(7, _translate("MainWindow", "smtp.sohu.com"))
        self.comboBox_TextEmailsmtpserver.setItemText(8, _translate("MainWindow", "smtp.china.com"))
        self.groupBox_7.setTitle(_translate("MainWindow", "发件人"))
        self.label_TextEmailsenderemail.setText(_translate("MainWindow", "邮箱"))
        self.label_TextEmailsenderpassword.setText(_translate("MainWindow", "授权码"))
        self.groupBox_8.setTitle(_translate("MainWindow", "收件人"))
        self.label_TextEmailreceiveremail.setText(_translate("MainWindow", "邮箱"))
        self.groupBox_9.setTitle(_translate("MainWindow", "属性"))
        self.label_TextEmailtitle.setText(_translate("MainWindow", "标题"))
        self.btn_TextEmailclearcontent.setText(_translate("MainWindow", "清空内容"))
        self.btn_TextEmailSend.setText(_translate("MainWindow", "发送"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.TextEmail), _translate("MainWindow", "文本邮件"))
        self.groupBox_11.setTitle(_translate("MainWindow", "服务器"))
        self.label_FileEmailsmtpserver.setText(_translate("MainWindow", "服务器"))
        self.comboBox_FileEmailsmtpserver.setItemText(0, _translate("MainWindow", "smtp.aliyun.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(1, _translate("MainWindow", "smtp.gmail.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(2, _translate("MainWindow", "smtp.sina.com.cn"))
        self.comboBox_FileEmailsmtpserver.setItemText(3, _translate("MainWindow", "smtp.tom.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(4, _translate("MainWindow", "smtp.163.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(5, _translate("MainWindow", "smtp.126.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(6, _translate("MainWindow", "smtp.qq.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(7, _translate("MainWindow", "smtp.sohu.com"))
        self.comboBox_FileEmailsmtpserver.setItemText(8, _translate("MainWindow", "smtp.china.com"))
        self.groupBox_12.setTitle(_translate("MainWindow", "发件人"))
        self.label_FileEmailsenderemail.setText(_translate("MainWindow", "邮箱"))
        self.label_FileEmailsenderpassword.setText(_translate("MainWindow", "授权码"))
        self.groupBox_13.setTitle(_translate("MainWindow", "收件人"))
        self.label_FileEmailreceiveremail.setText(_translate("MainWindow", "邮箱"))
        self.groupBox_14.setTitle(_translate("MainWindow", "属性"))
        self.label_FileEmailtitle.setText(_translate("MainWindow", "标题"))
        self.groupBox_15.setTitle(_translate("MainWindow", "附件"))
        self.btn_FindFileEmail.setText(_translate("MainWindow", "附件"))
        self.btn_FileEmailclearcontent.setText(_translate("MainWindow", "清空内容"))
        self.btn_FileEmailSend.setText(_translate("MainWindow", "发送"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.FileEmail), _translate("MainWindow", "附件邮件"))
        self.groupBox_10.setTitle(_translate("MainWindow", "编辑正文"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab), _translate("MainWindow", "状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Email), _translate("MainWindow", "邮件"))
